CREATE DATABASE BI_NDS
GO
USE BI_NDS
GO

CREATE TABLE VENDOR(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	VendorID VARCHAR(50),
	VendorName VARCHAR(50),
	NguonDL INT,
	NgayCapNhat DATETIME,
	TrangThai INT,
	NgayTao DATETIME
)
--SET IDENTITY_INSERT [BI_NDS].[dbo].[VENDOR] ON
GO
CREATE TABLE PAYMENT_TYPE(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	PaymentTypeCode VARCHAR(10),
	PaymentTypeName VARCHAR(50),
	NguonDL INT,
	NgayCapNhat DATETIME,
	TrangThai INT,
	NgayTao DATETIME
)
--SET IDENTITY_INSERT [BI_NDS].[dbo].[PAYMENT_TYPE] ON
GO
CREATE TABLE PICK_UP(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	PULongtitude VARCHAR(100),
	PULattitude VARCHAR(100),
	PUDatetime DATETIME,
	NumberPU VARCHAR(100),
	StreetPU VARCHAR(100),
	CityPU VARCHAR(100),
	StatePU VARCHAR(100),
	BoroughPU INT,
	PUCensusTractCode VARCHAR(100),
	PUCensusBlockCode VARCHAR(100),
	PUCensusBlockGroup VARCHAR(100),
	NguonDL INT,
	NgayCapNhat DATETIME,
	TrangThai INT,
	NgayTao DATETIME
)
--SET IDENTITY_INSERT [BI_NDS].[dbo].[PICK_UP] ON
GO
CREATE TABLE DROP_OFF(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	DOLongtitude VARCHAR(100),
	DOLattitude VARCHAR(100),
	DODatetime DATETIME,
	NumberDO VARCHAR(100),
	StreetDO VARCHAR(100),
	CityDO VARCHAR(100),
	StateDO VARCHAR(100),
	BoroughDO INT,
	DOCensusTractCode VARCHAR(100),
	DOCensusBlockCode VARCHAR(100),
	DOCensusBlockGroup VARCHAR(100),
	NguonDL INT,
	NgayCapNhat DATETIME,
	TrangThai INT,
	NgayTao DATETIME
)
--SET IDENTITY_INSERT [BI_NDS].[dbo].[DROP_OFF] ON
GO
CREATE TABLE BILL(
	BillID INT IDENTITY(1,1) PRIMARY KEY,
	VendorID INT,
	PUID INT,
	DOID INT,
	Extra FLOAT,
	FareAmount FLOAT,
	MtaTax FLOAT,
	PassCount INT,
	PaymentType INT,
	RateCode VARCHAR(50),
	StoreAndFwd VARCHAR(10),
	TipAmount FLOAT,
	TollsAmount FLOAT,
	TotalAmount FLOAT,
	TripDistance FLOAT,
	NguonDL INT,
	NgayCapNhat DATETIME,
	TrangThai INT,
	NgayTao DATETIME
)
--SET IDENTITY_INSERT [BI_NDS].[dbo].[BILL] ON
GO
CREATE TABLE BORO(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	BoroCode VARCHAR(100),
	BoroName VARCHAR(100),
	BoroCT2010 VARCHAR(100),
	CTLabel VARCHAR(100),
	CT2010 VARCHAR(100),
	CDELigibil NVARCHAR(100),
	NguonDL INT,
	NgayCapNhat DATETIME,
	TrangThai INT,
	NgayTao DATETIME
)
--SET IDENTITY_INSERT [BI_NDS].[dbo].[BORO] ON
GO
CREATE TABLE NTA(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NTACode VARCHAR(100),
	NTAName VARCHAR(100),
	BOROID INT,
	PUMA VARCHAR(100),
	NguonDL INT,
	NgayCapNhat DATETIME,
	TrangThai INT,
	NgayTao DATETIME
)
--SET IDENTITY_INSERT [BI_NDS].[dbo].[NTA] ON
GO
CREATE TABLE NGUONDULIEU
(
	ID INT IDENTITY (1,1) PRIMARY KEY,
	TenNguonDL NVARCHAR(50)
)
--SET IDENTITY_INSERT [BI_NDS].[dbo].[NGUONDULIEU] ON
GO

CREATE TABLE TRANGTHAI
(
	ID INT IDENTITY (1,1) PRIMARY KEY,
	TrangThai NVARCHAR(50)
)
--SET IDENTITY_INSERT [BI_NDS].[dbo].[TRANGTHAI] ON
GO

ALTER TABLE BILL ADD CONSTRAINT FK_VENDOR_BILL FOREIGN KEY (VendorID) REFERENCES VENDOR(ID)
ALTER TABLE BILL ADD CONSTRAINT FK_PAYMENTTYPE_BILL FOREIGN KEY (PaymentType) REFERENCES PAYMENT_TYPE(ID)
ALTER TABLE BILL ADD CONSTRAINT FK_PICKUP_BILL FOREIGN KEY (PUID) REFERENCES PICK_UP(ID)
ALTER TABLE BILL ADD CONSTRAINT FK_DROPOFF_BILL FOREIGN KEY (DOID) REFERENCES DROP_OFF(ID)
ALTER TABLE NTA ADD CONSTRAINT FK_NTA_BORO FOREIGN KEY (BOROID) REFERENCES BORO(ID)
--ALTER TABLE PICK_UP ADD CONSTRAINT FK_PU_BORO FOREIGN KEY (BoroughPU) REFERENCES BORO(ID)
--ALTER TABLE DROP_OFF ADD CONSTRAINT FK_DO_BORO FOREIGN KEY (BoroughDO) REFERENCES BORO(ID)
ALTER TABLE VENDOR ADD CONSTRAINT FK_VENDOR_TRANGTHAI FOREIGN KEY (TrangThai) REFERENCES TRANGTHAI(ID)
ALTER TABLE PAYMENT_TYPE ADD CONSTRAINT FK_PAYMENT_TYPE_TRANGTHAI FOREIGN KEY (TrangThai) REFERENCES TRANGTHAI(ID)
ALTER TABLE PICK_UP ADD CONSTRAINT FK_PICK_UP_TRANGTHAI FOREIGN KEY (TrangThai) REFERENCES TRANGTHAI(ID)
ALTER TABLE DROP_OFF ADD CONSTRAINT FK_DROP_OFF_TRANGTHAI FOREIGN KEY (TrangThai) REFERENCES TRANGTHAI(ID)
ALTER TABLE BILL ADD CONSTRAINT FK_BILL_TRANGTHAI FOREIGN KEY (TrangThai) REFERENCES TRANGTHAI(ID)
ALTER TABLE BORO ADD CONSTRAINT FK_BORO_TRANGTHAI FOREIGN KEY (TrangThai) REFERENCES TRANGTHAI(ID)
ALTER TABLE NTA ADD CONSTRAINT FK_NTA_TRANGTHAI FOREIGN KEY (TrangThai) REFERENCES TRANGTHAI(ID)
ALTER TABLE VENDOR ADD CONSTRAINT FK_VENDOR_NGUONDULIEU FOREIGN KEY (NguonDL) REFERENCES NGUONDULIEU(ID)
ALTER TABLE PAYMENT_TYPE ADD CONSTRAINT FK_PAYMENT_TYPE_NGUONDULIEU FOREIGN KEY (NguonDL) REFERENCES NGUONDULIEU(ID)
ALTER TABLE PICK_UP ADD CONSTRAINT FK_PICK_UP_NGUONDULIEU FOREIGN KEY (NguonDL) REFERENCES NGUONDULIEU(ID)
ALTER TABLE DROP_OFF ADD CONSTRAINT FK_DROP_OFF_NGUONDULIEU FOREIGN KEY (NguonDL) REFERENCES NGUONDULIEU(ID)
ALTER TABLE BILL ADD CONSTRAINT FK_BILL_NGUONDULIEU FOREIGN KEY (NguonDL) REFERENCES NGUONDULIEU(ID)
ALTER TABLE BORO ADD CONSTRAINT FK_BORO_NGUONDULIEU FOREIGN KEY (NguonDL) REFERENCES NGUONDULIEU(ID)
ALTER TABLE NTA ADD CONSTRAINT FK_NTA_NGUONDULIEU FOREIGN KEY (NguonDL) REFERENCES NGUONDULIEU(ID)
ALTER TABLE PICK_UP ADD CONSTRAINT FK_PICK_UP_BORO FOREIGN KEY (NguonDL) REFERENCES BORO(ID)
ALTER TABLE DROP_OFF ADD CONSTRAINT FK_DROP_OFF_BORO FOREIGN KEY (NguonDL) REFERENCES BORO(ID)

INSERT INTO NGUONDULIEU(TenNguonDL) VALUES ('YELLOWTAXI'),('CENSUSBLOCK')
GO
INSERT INTO TRANGTHAI(TrangThai) VALUES ('Dang hoat dong'),('Han che')
GO

INSERT INTO VENDOR(VendorID,VendorName, NguonDL, NgayCapNhat, TrangThai) VALUES(1,'Creative Mobile Technologies', 1, '20201212 22:11:11.823', 1);
INSERT INTO VENDOR(VendorID,VendorName, NguonDL, NgayCapNhat, TrangThai) VALUES(2,'VeriFone Inc', 1, '20201212 22:11:11.823', 1);
INSERT INTO VENDOR(VendorID,VendorName, NguonDL, NgayCapNhat, TrangThai) VALUES(3,'Digital Dispatch System', 1, '20201212 22:11:11.823', 1);

INSERT INTO PAYMENT_TYPE(PaymentTypeCode,PaymentTypeName, NguonDL, NgayCapNhat, TrangThai) VALUES(1, 'The tin dung', 1, '20201212 22:11:11.823', 1)
INSERT INTO PAYMENT_TYPE(PaymentTypeCode,PaymentTypeName, NguonDL, NgayCapNhat, TrangThai) VALUES(2, 'Tien mat', 1, '20201212 22:11:11.823', 1)
INSERT INTO PAYMENT_TYPE(PaymentTypeCode,PaymentTypeName, NguonDL, NgayCapNhat, TrangThai) VALUES(3, 'Khong tinh phi', 1, '20201212 22:11:11.823', 1)
INSERT INTO PAYMENT_TYPE(PaymentTypeCode,PaymentTypeName, NguonDL, NgayCapNhat, TrangThai) VALUES(4, 'Tranh chap', 1, '20201212 22:11:11.823', 1)
INSERT INTO PAYMENT_TYPE(PaymentTypeCode,PaymentTypeName, NguonDL, NgayCapNhat, TrangThai) VALUES(5, 'Khong xac dinh', 1, '20201212 22:11:11.823', 1)
INSERT INTO PAYMENT_TYPE(PaymentTypeCode,PaymentTypeName, NguonDL, NgayCapNhat, TrangThai) VALUES(6, 'Chuyen di bi hoan', 1, '20201212 22:11:11.823', 1)

UPDATE VENDOR SET NguonDL = 1, NgayCapNhat = '20201212 22:11:11.823', TrangThai = 1;
UPDATE PAYMENT_TYPE SET NguonDL = 1, NgayCapNhat = '20201212 22:11:11.823', TrangThai = 1;



INSERT INTO BORO(BOROCODE,BORONAME, NguonDL, NgayCapNhat, TrangThai) VALUES (1,'Manhattan', 1, '20201212 22:11:11.823', 1)
INSERT INTO BORO(BOROCODE,BORONAME, NguonDL, NgayCapNhat, TrangThai) VALUES (2,'Bronx', 1, '20201212 22:11:11.823', 1)
INSERT INTO BORO(BOROCODE,BORONAME, NguonDL, NgayCapNhat, TrangThai) VALUES (3,'Brooklyn', 1, '20201212 22:11:11.823', 1)
INSERT INTO BORO(BOROCODE,BORONAME, NguonDL, NgayCapNhat, TrangThai) VALUES (4,'Queens', 1, '20201212 22:11:11.823', 1)
INSERT INTO BORO(BOROCODE,BORONAME, NguonDL, NgayCapNhat, TrangThai) VALUES (5,'Staten Island', 1, '20201212 22:11:11.823', 1)